ValueError exception from ambiguous truth value
This prevents the following ValueError exception

  File "vispy/scene/cameras/panzoom.py", line 89, in zoom
    center = center or self.center
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

by checking if center is none.