Fix TypeError for membership test of KeyboardModifiers per #2212 (#2293)
KeyboardModifiers follows from C++ QFlags<> which is closer to set-like semantics,
even if its implementation may be a bit field. Swapping to `qtmod & q` lets it
perform properly as a result.

This was triggering in SIFT 1.2.3 on mouseMove events as
```
TypeError: unsupported operand type(s) for &: 'KeyboardModifier' and 'KeyboardModifiers'
```